apiVersion: v1
kind: Service
metadata:
  name: reactjs-service
spec:
  selector:
    app: reactjs-service
  ports:
    - port: 8080
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactjs-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactjs-service
  template:
    metadata:
      labels:
        app: reactjs-service
    spec:
      containers:
        - name: reactjs-service
          image: prit30/c6-react-image:v1
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "2"
              memory: "1024Mi"
            requests:
              cpu: "0.10"
              memory: "200Mi"
---

